version: '3'

services:
  pgsql:
    image: postgres:11-alpine
    ports:
      - '5435:5432'
    container_name: 'pg_monolito'
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pg_monolito

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    container_name: 'monolito'
    restart: always
    volumes:
      - .:/app
